# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'News Challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for News Challenge
  pod 'Alamofire'

  target 'News ChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'News ChallengeUITests' do
    # Pods for testing
  end

end
